env:
  global:
    - GH_REF: github.com/nhz-io/babel-plugin-mocktail
language: node_js
node_js:
- '4.2'
script: npm run-script travis
deploy:
  provider: npm
  email: dev@nhz.io
  skip_cleanup: true
  api_key:
    secure: ajSVID6cDt3UwrYQ6N/S7FoxIjKwZYqafEbZM7pYZIfvlLm+pw3K1EY6Wpv7KAHsVZ3fuZ7kUHd/zyA5rWO72/cnIMLp4hNB2dpqj2eQdN2e066bohHm8oq/keaigmxm4SYjudNolg+XoSy2s28bZe8nc7o3tHr/hgsxUH1nj7AUQQCyN1C2KokIj411+dxnbvijHUatoJiXbQtJJfJfF86A4kVJUCBBTF9tG8fQ1UxA+nwopmpPN14jDfI9B4kOpOHOB21KiiQ1KzolSWt3x2NaJhF+cqeUaYm5Od7UtzyjV0p1sjM16rHh0hqXiewRXmeKizrOyNau+Q1+UGhdHF+JP3hDwavhHgpuLIYDw9AaJ0w1roVYW/HIKCxaaWGxuCvN/U/tOS+Rg0pQCvtGCiJrzYz4apbgKSwZRRIG8pVPXuziLyHcotxVAV1TZJUx1uneSNPpzYqd1ydqVAJ3AfVZaDeHaTTJJu8fsJgoiVAxFFOnPmf6K08mXX2/4PRIwnDjoeCImZHwl39+6hSkHcWzQkYYVUHe2jdSjMbGXKXzEi6m8I64+v0rD2SF3niGiqmv9IiyJYF+Y6z1USBEOCsQsy7XjmX4oRqVt8lA0L5L5lBwRlBpFTRNYe/2GGSfm9GqVem/c417FfpTDKvwQy0RWqcVpObJS7XGGO/x6Us=
  on:
    repo: nhz-io/babel-plugin-mocktail
    branch: master

  after_deploy:
  - bash ./gh-pages.sh
