env:
  global:
  - GH_REF: github.com/nhz-io/babel-plugin-mocktail
  - secure: N51+1bl6LA0Cg47KDCuU0LNTA+18uuzbn4DdePoUjVqFEwOUyPosOGv4ETlZyP9k8MUDLa+4ZyPZT9bzHjjIB9fq+9KKwUVYvK6PUwGV4yC4PLNL7ESiHGJNNLWyTrBn1K3lawtiWistI/DxtFUMvDCojKIp1+CJp9+WizDvYObv/nbzj8PMLvhicibLYnD6UIXVk0eCURr2ekrygC6lF35wA1agy0qXtoqTrqF00jd/e0mSVlUvKLj83RZkgYPO26oayg+IHOp2jvoV0km/kH8NjQTpxYyMNyU7p6kezChch0JLjPhUtQnlaQo9w2XpfFINMw3PgW9k+jhH1/cON7FgDm9q/aIy0lZU+oq1dEBCMfGP7nuU7qMnmqcdKy7Cwuvn3wTpp0C8ornzz42qD+WxWdZOnuWXxpd9/XmWyPcfhADHhC74FImvKlQjDxMWDuhPDkuv5vNEXAdAPU/YyRUyfLe42JFSvaxdcLcf8uKsMBgnMXxn/iOajQVD5xYku7n8FUm2Yp3s30npXaWFoptf8dF1finmQPuRc6CMqPz7ghQo6KH0reK4QHGUwgeGkIK3h19S4YEXEKijiZyTl6X6jE+dYh88PWefHzsoievhmo4oiKbmf4WVAXrPX8yd1TXJexSexm+mtkoAJMTrGODWvlPsjO749MveuLGmA0c=
language: node_js
node_js:
- '4.2'
script: npm run-script travis
deploy:
  provider: npm
  email: dev@nhz.io
  skip_cleanup: true
  api_key:
    secure: ajSVID6cDt3UwrYQ6N/S7FoxIjKwZYqafEbZM7pYZIfvlLm+pw3K1EY6Wpv7KAHsVZ3fuZ7kUHd/zyA5rWO72/cnIMLp4hNB2dpqj2eQdN2e066bohHm8oq/keaigmxm4SYjudNolg+XoSy2s28bZe8nc7o3tHr/hgsxUH1nj7AUQQCyN1C2KokIj411+dxnbvijHUatoJiXbQtJJfJfF86A4kVJUCBBTF9tG8fQ1UxA+nwopmpPN14jDfI9B4kOpOHOB21KiiQ1KzolSWt3x2NaJhF+cqeUaYm5Od7UtzyjV0p1sjM16rHh0hqXiewRXmeKizrOyNau+Q1+UGhdHF+JP3hDwavhHgpuLIYDw9AaJ0w1roVYW/HIKCxaaWGxuCvN/U/tOS+Rg0pQCvtGCiJrzYz4apbgKSwZRRIG8pVPXuziLyHcotxVAV1TZJUx1uneSNPpzYqd1ydqVAJ3AfVZaDeHaTTJJu8fsJgoiVAxFFOnPmf6K08mXX2/4PRIwnDjoeCImZHwl39+6hSkHcWzQkYYVUHe2jdSjMbGXKXzEi6m8I64+v0rD2SF3niGiqmv9IiyJYF+Y6z1USBEOCsQsy7XjmX4oRqVt8lA0L5L5lBwRlBpFTRNYe/2GGSfm9GqVem/c417FfpTDKvwQy0RWqcVpObJS7XGGO/x6Us=
  on:
    repo: nhz-io/babel-plugin-mocktail
    branch: master
after_deploy:
- bash ./gh-pages.sh
- npm run-script coveralls
