language: node_js
node_js:
- '4.2'
script: npm run-script travis
deploy:
  provider: npm
  email: dev@nhz.io
  api_key:
    secure: G9pMuRHFX8PZ4gbIufo556THN/bJMmiX/QaczTdsTypUyPDn+UQe2Q4gDlCNNDZLH3AlgSSe45OgHpu5ogPvpfcmXiL4yQfBpSM0kyVlPZMnNjUF6CxgZGDfvmXkcs7fCMWwkeSr9I8hpvr+La2oMWnN3AO6AWkpzNV6Y9KsNYeGCvI8IhdDgn1EkdJ4kV+9arEx3xugeTpTxHWK6cnYunmCWwUV5V+v5taKPKvbvn2iudkLaYfuoXCmuKZM39l7w5GHqW8L2yzCb4fyzuk09gVHv9IPP04IzbBK+0SxCUCoWDo3cMjZs2zZAc/DA6PYaXWlqOkQpY/7Iyz0JBN8tuDe4sm0HeedZvyndLgKAcf8m9Mceqkg1acKSJz7J7KC0JN4hkYa8JAZBEujyZsyw/aIwUEfFU45jOd7m8JDXUm2i4AOarc+C1JHT2r9qQC+LEy9EW47T1UlIrcSgXhR4xsgfC4Y9owlER3CDsgJuULcz8PamVHpCUDdAcmQrGK5CdT1JRGnXUMg6smwQ5cWomkR08Phxw7ekgDA7VMJi2KxsCNVnAVHMkfoZDm4HnPCq7yzN+cNHGlOU6W9kl3bvt6emEYXnVieEs+1A0kdiJWLi6g73GJA+sAQzlHkn41rbcFFtK8EoXGhjtb1EbqMHf+3ZLzfN/+SoED6W9mfn3U=
  on:
    repo: nhz-io/babel-plugin-mocktail
    branch: master
